//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "images")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    pub user_pid: Option<Uuid>,
    pub public: bool,
    #[sea_orm(column_type = "Text")]
    pub raw_name: String,
    pub size: String,
    #[sea_orm(column_type = "Text")]
    pub file_name: String,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    pub location: Location,
}

#[derive(Clone, Copy, Debug, EnumIter, PartialEq, Eq, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(enum_name = "location", rs_type = "String", db_type = "Enum")]
#[serde(rename_all = "lowercase")]
pub enum Location {
    #[sea_orm(string_value = "local")]
    Local,
    #[sea_orm(string_value = "r2")]
    R2,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
